stages:
  - lint
  - test
  - build

lint:
  image: python:3.11
  stage: lint
  before_script:
    - pip install ruff
  script:
    - ruff backend/

test:
  image: python:3.11
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python backend/manage.py test

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker build -t mangalib-backend .
