version: '3.9'

services:
  web:
    build: .
    command: python backend\manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/code
    env_file:
      - backend/.env
    depends_on:
      - redis
